### ISSUE TITLE
🚩 Cannot run "./InstallNerdFont.ps1" command  [via💻Windows 11 21H2]

### ISSUE THREAD

**Issue by ohsevin** [Austinsuyoyo/InstallNerdFonts#1]
```
At C:\Users\{Username}\Downloads\InstallNerdFonts\utils\Write-Menu.psm1:420 char:48
+     [System.Console]::WriteLine("(`â†‘)UP (â†“)DOWN (â†
```

This is what my Windows Terminal (PowerShell w/Admin) or any other terminal I attempt to use for that matter--issues when I attempt to run your script from within the git cloned directory using `./InstallNerdFont.ps1`

Any ideas? I'm not familiar with this issue, it may be a typo in the script at that line / char?

**Example:**
<img width="418" alt="InstallNerdFont-script-issues" src="https://user-images.githubusercontent.com/31463232/158674232-084a47a4-2215-4dbf-836a-b256943e95fc.png">

**Comment by Austinsuyoyo** [comment]
that char is a arrow symbol like below
```
(↑)UP (↓)DOWN (←) Previous page (→) Next page (Enter) Confirm selection (Esc) Exit
```

maybe just delete the arrow then test again?
